package com.min01.beyondtheabyss.entity.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class GhidruthAnimation 
{
	public static final AnimationDefinition GHIDRUTH_SWIM = AnimationDefinition.Builder.withLength(2f).looping()
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 4f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, -4f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-4.96f, -10.01f, -0.22f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(9.91f, 10.04f, -0.44f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftFin",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftFin", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RearBody",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RearBody", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -20f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 20f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Tail",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightFin",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightFin", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("root2", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167667f, KeyframeAnimations.posVec(-8f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3433333f, KeyframeAnimations.posVec(8f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("root2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();
	public static final AnimationDefinition GHIDRUTH_BITE = AnimationDefinition.Builder.withLength(1.0416767f)
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 37f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0f, 40.83f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 0f, 12.66f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, -4.51f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(6.25f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0416767f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(20.17f, -21.25f, -7.58f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(16.14f, -17f, -6.07f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-10.46f, 14.31f, -9.48f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RearBody", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0416767f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RearBody", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, -41.25f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -10.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, -52.87f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Tail", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0416767f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 3.75f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 25.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, -3.37f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Mouth", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0416767f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Mouth", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(41.25f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(55.5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-3.37f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.build();
	public static final AnimationDefinition GHIDRUTH_LUNGE = AnimationDefinition.Builder.withLength(0.8343334f)
			.addAnimation("MainRootThing", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.20834334f, KeyframeAnimations.posVec(-8f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3433333f, KeyframeAnimations.posVec(-8f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.posVec(8f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("MainRootThing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(11.88f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 4f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 4f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, -4f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-4.96f, -10.01f, -0.22f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-4.96f, -10.01f, -0.22f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-2.59f, 10.04f, -0.44f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-22.5f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-22.5f, -10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(10f, 10f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftFin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightFin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RearBody",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(22.5f, -20f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(22.5f, -20f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(7.5f, 20f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(22.5f, -7.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(22.5f, -7.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();
	public static final AnimationDefinition GHIDRUTH_TAIL_SWING = AnimationDefinition.Builder.withLength(1f)
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 32f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 0f, 32f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(22.5f, 67.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(22.5f, 67.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625f, KeyframeAnimations.degreeVec(12.5f, -56.25f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RearBody",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RearBody", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Tail",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Mouth",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Mouth", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.CATMULLROM)))
			.build();
}
